# Template de un Cluster multinodo en Kind.

apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: reditos-cluster

nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80
        hostPort: 8080
      - containerPort: 443
        hostPort: 8443
    extraMounts:
      - hostPath: /home/reditos/shared
        containerPath: /mnt/shared
  - role: worker
  - role: worker
